/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PtgAccordion {
        "bgColor"?: string;
        /**
          * @default false
         */
        "defaultOpened": boolean;
        "description": string;
        "label": string;
    }
    interface PtgAlert {
        "appreanced": string;
        "buttoncss": string;
        "texed": string;
    }
    interface PtgBreadcrumbs {
        /**
          * @default []
         */
        "datalist": any;
    }
    interface PtgButton {
        "appearance": string;
        /**
          * @default 'right'
         */
        "btnIconAlignment"?: string;
        /**
          * @default ""
         */
        "text"?: string;
    }
    interface PtgCalender {
        "callback"?: (val: any) => void;
        /**
          * @default ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']
         */
        "dayNames": string[];
        /**
          * @default [     'January',     'February',     'March',     'April',     'May',     'June',     'July',     'August',     'September',     'October',     'November',     'December',   ]
         */
        "monthNames": string[];
        /**
          * @default true
         */
        "showFillDays": boolean;
        "startDate": any;
    }
    interface PtgCard {
        /**
          * @default 'select'
         */
        "cardButtonText": string;
        /**
          * @default ''
         */
        "cardContent": string;
        "cardContentLength"?: number;
        "cardId": number;
        /**
          * @default ''
         */
        "cardTitle": string;
        /**
          * @default false
         */
        "isCardAction": boolean;
        /**
          * @default ''
         */
        "src": string;
    }
    interface PtgCheckbox {
        "callback"?: (val: any) => void;
        /**
          * The first name
         */
        "checked"?: boolean;
        "color"?: string;
        "dataid": any;
        "datavalue": any;
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        "label"?: string;
    }
    interface PtgFooter {
        "footer": string;
    }
    interface PtgHeader {
        "header": string;
    }
    interface PtgInput {
        /**
          * id for input
         */
        "inputId": string;
        /**
          * label for inout
         */
        "label": string;
        /**
          * name for inout
         */
        "name": string;
        /**
          * The placeholder
          * @default ''
         */
        "placeholder": string;
        /**
          * type of input
         */
        "type": string;
        /**
          * name for inout
          * @default ''
         */
        "value": string;
        /**
          * @default '100%'
         */
        "width": string;
    }
    interface PtgModal {
        /**
          * @default ''
         */
        "btnName": string;
        /**
          * @default 'secondary'
         */
        "cancelBtn": string;
        /**
          * @default false
         */
        "closeOutsideClick": boolean;
        /**
          * @default 'Confirm'
         */
        "confirmButtonName": string;
        /**
          * @default false
         */
        "isOpen": boolean;
        /**
          * @default 'Modal Header'
         */
        "modalHeaderName": string;
        /**
          * @default 'md'
         */
        "modalSize": string;
        /**
          * @default 'primary'
         */
        "primaryBtn": string;
        /**
          * @default true
         */
        "showFooter": boolean;
        /**
          * @default true
         */
        "showHeader": boolean;
    }
    interface PtgPagination {
        "itemCount": number;
        /**
          * @default 0
         */
        "page": number;
        /**
          * @default 10
         */
        "pageSize": number;
        /**
          * @default []
         */
        "pageSizeOptions": number[];
    }
    interface PtgRadiobtn {
        "ids": string;
        "name": string;
        "sender": string;
        "type": string;
        "value": string;
    }
    interface PtgRadiobuton {
        "ids": string;
        "name": string;
        "sender": string;
        "type": string;
        "value": string;
    }
    interface PtgSelect {
        /**
          * @default false
         */
        "multiSelect": boolean;
        "selectData": any;
    }
    interface PtgSidenav {
        "text": string;
        "url": string;
    }
    interface PtgSpinner {
        "appearance": string;
    }
    interface PtgTable {
        "customClass"?: string;
        /**
          * @default []
         */
        "pageSizeOptions": number[];
        /**
          * @default false
         */
        "searchable": boolean;
        /**
          * @default false
         */
        "sortable": boolean;
        "tableHover"?: boolean;
        "tableStrip"?: boolean;
        "tablecolumn": any;
        "tabledata": any;
        "tabletitle": string;
        "themeColor"?: string;
    }
    interface PtgTextarea {
        "appearance": string;
        "autofocus": boolean;
        "cols": number;
        "disable": boolean;
        "form": string;
        "maxlen": number;
        "minlength": number;
        "name": string;
        "placeholder": string;
        "readonly": boolean;
        "required": boolean;
        "rows": number;
        "value": string;
    }
    interface PtgToast {
        "appearance": string;
        "discription": string;
        "id1": string;
        /**
          * @default false
         */
        "open": boolean;
        "type": string;
    }
    interface PtgUiCarousel {
        /**
          * @default []
         */
        "images": Array<string>;
        /**
          * @default '200'
         */
        "imgHeight": string;
        /**
          * @default '200'
         */
        "imgWidth": string;
        /**
          * @default true
         */
        "showIndicators": boolean;
    }
}
export interface PtgCalenderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtgCalenderElement;
}
export interface PtgCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtgCardElement;
}
export interface PtgCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtgCheckboxElement;
}
export interface PtgInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtgInputElement;
}
export interface PtgModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtgModalElement;
}
export interface PtgPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPtgPaginationElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPtgAccordionElement extends Components.PtgAccordion, HTMLStencilElement {
    }
    var HTMLPtgAccordionElement: {
        prototype: HTMLPtgAccordionElement;
        new (): HTMLPtgAccordionElement;
    };
    interface HTMLPtgAlertElement extends Components.PtgAlert, HTMLStencilElement {
    }
    var HTMLPtgAlertElement: {
        prototype: HTMLPtgAlertElement;
        new (): HTMLPtgAlertElement;
    };
    interface HTMLPtgBreadcrumbsElement extends Components.PtgBreadcrumbs, HTMLStencilElement {
    }
    var HTMLPtgBreadcrumbsElement: {
        prototype: HTMLPtgBreadcrumbsElement;
        new (): HTMLPtgBreadcrumbsElement;
    };
    interface HTMLPtgButtonElement extends Components.PtgButton, HTMLStencilElement {
    }
    var HTMLPtgButtonElement: {
        prototype: HTMLPtgButtonElement;
        new (): HTMLPtgButtonElement;
    };
    interface HTMLPtgCalenderElementEventMap {
        "dayChanged": any;
        "monthChanged": any;
    }
    interface HTMLPtgCalenderElement extends Components.PtgCalender, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPtgCalenderElementEventMap>(type: K, listener: (this: HTMLPtgCalenderElement, ev: PtgCalenderCustomEvent<HTMLPtgCalenderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPtgCalenderElementEventMap>(type: K, listener: (this: HTMLPtgCalenderElement, ev: PtgCalenderCustomEvent<HTMLPtgCalenderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPtgCalenderElement: {
        prototype: HTMLPtgCalenderElement;
        new (): HTMLPtgCalenderElement;
    };
    interface HTMLPtgCardElementEventMap {
        "handleClick": any;
    }
    interface HTMLPtgCardElement extends Components.PtgCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPtgCardElementEventMap>(type: K, listener: (this: HTMLPtgCardElement, ev: PtgCardCustomEvent<HTMLPtgCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPtgCardElementEventMap>(type: K, listener: (this: HTMLPtgCardElement, ev: PtgCardCustomEvent<HTMLPtgCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPtgCardElement: {
        prototype: HTMLPtgCardElement;
        new (): HTMLPtgCardElement;
    };
    interface HTMLPtgCheckboxElementEventMap {
        "valueChanged": string;
    }
    interface HTMLPtgCheckboxElement extends Components.PtgCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPtgCheckboxElementEventMap>(type: K, listener: (this: HTMLPtgCheckboxElement, ev: PtgCheckboxCustomEvent<HTMLPtgCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPtgCheckboxElementEventMap>(type: K, listener: (this: HTMLPtgCheckboxElement, ev: PtgCheckboxCustomEvent<HTMLPtgCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPtgCheckboxElement: {
        prototype: HTMLPtgCheckboxElement;
        new (): HTMLPtgCheckboxElement;
    };
    interface HTMLPtgFooterElement extends Components.PtgFooter, HTMLStencilElement {
    }
    var HTMLPtgFooterElement: {
        prototype: HTMLPtgFooterElement;
        new (): HTMLPtgFooterElement;
    };
    interface HTMLPtgHeaderElement extends Components.PtgHeader, HTMLStencilElement {
    }
    var HTMLPtgHeaderElement: {
        prototype: HTMLPtgHeaderElement;
        new (): HTMLPtgHeaderElement;
    };
    interface HTMLPtgInputElementEventMap {
        "valueChanged": string;
    }
    interface HTMLPtgInputElement extends Components.PtgInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPtgInputElementEventMap>(type: K, listener: (this: HTMLPtgInputElement, ev: PtgInputCustomEvent<HTMLPtgInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPtgInputElementEventMap>(type: K, listener: (this: HTMLPtgInputElement, ev: PtgInputCustomEvent<HTMLPtgInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPtgInputElement: {
        prototype: HTMLPtgInputElement;
        new (): HTMLPtgInputElement;
    };
    interface HTMLPtgModalElementEventMap {
        "modalClose": boolean;
        "confirmClose": boolean;
    }
    interface HTMLPtgModalElement extends Components.PtgModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPtgModalElementEventMap>(type: K, listener: (this: HTMLPtgModalElement, ev: PtgModalCustomEvent<HTMLPtgModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPtgModalElementEventMap>(type: K, listener: (this: HTMLPtgModalElement, ev: PtgModalCustomEvent<HTMLPtgModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPtgModalElement: {
        prototype: HTMLPtgModalElement;
        new (): HTMLPtgModalElement;
    };
    interface HTMLPtgPaginationElementEventMap {
        "pageChanged": any;
        "sizeChanged": any;
    }
    interface HTMLPtgPaginationElement extends Components.PtgPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPtgPaginationElementEventMap>(type: K, listener: (this: HTMLPtgPaginationElement, ev: PtgPaginationCustomEvent<HTMLPtgPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPtgPaginationElementEventMap>(type: K, listener: (this: HTMLPtgPaginationElement, ev: PtgPaginationCustomEvent<HTMLPtgPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPtgPaginationElement: {
        prototype: HTMLPtgPaginationElement;
        new (): HTMLPtgPaginationElement;
    };
    interface HTMLPtgRadiobtnElement extends Components.PtgRadiobtn, HTMLStencilElement {
    }
    var HTMLPtgRadiobtnElement: {
        prototype: HTMLPtgRadiobtnElement;
        new (): HTMLPtgRadiobtnElement;
    };
    interface HTMLPtgRadiobutonElement extends Components.PtgRadiobuton, HTMLStencilElement {
    }
    var HTMLPtgRadiobutonElement: {
        prototype: HTMLPtgRadiobutonElement;
        new (): HTMLPtgRadiobutonElement;
    };
    interface HTMLPtgSelectElement extends Components.PtgSelect, HTMLStencilElement {
    }
    var HTMLPtgSelectElement: {
        prototype: HTMLPtgSelectElement;
        new (): HTMLPtgSelectElement;
    };
    interface HTMLPtgSidenavElement extends Components.PtgSidenav, HTMLStencilElement {
    }
    var HTMLPtgSidenavElement: {
        prototype: HTMLPtgSidenavElement;
        new (): HTMLPtgSidenavElement;
    };
    interface HTMLPtgSpinnerElement extends Components.PtgSpinner, HTMLStencilElement {
    }
    var HTMLPtgSpinnerElement: {
        prototype: HTMLPtgSpinnerElement;
        new (): HTMLPtgSpinnerElement;
    };
    interface HTMLPtgTableElement extends Components.PtgTable, HTMLStencilElement {
    }
    var HTMLPtgTableElement: {
        prototype: HTMLPtgTableElement;
        new (): HTMLPtgTableElement;
    };
    interface HTMLPtgTextareaElement extends Components.PtgTextarea, HTMLStencilElement {
    }
    var HTMLPtgTextareaElement: {
        prototype: HTMLPtgTextareaElement;
        new (): HTMLPtgTextareaElement;
    };
    interface HTMLPtgToastElement extends Components.PtgToast, HTMLStencilElement {
    }
    var HTMLPtgToastElement: {
        prototype: HTMLPtgToastElement;
        new (): HTMLPtgToastElement;
    };
    interface HTMLPtgUiCarouselElement extends Components.PtgUiCarousel, HTMLStencilElement {
    }
    var HTMLPtgUiCarouselElement: {
        prototype: HTMLPtgUiCarouselElement;
        new (): HTMLPtgUiCarouselElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ptg-accordion": HTMLPtgAccordionElement;
        "ptg-alert": HTMLPtgAlertElement;
        "ptg-breadcrumbs": HTMLPtgBreadcrumbsElement;
        "ptg-button": HTMLPtgButtonElement;
        "ptg-calender": HTMLPtgCalenderElement;
        "ptg-card": HTMLPtgCardElement;
        "ptg-checkbox": HTMLPtgCheckboxElement;
        "ptg-footer": HTMLPtgFooterElement;
        "ptg-header": HTMLPtgHeaderElement;
        "ptg-input": HTMLPtgInputElement;
        "ptg-modal": HTMLPtgModalElement;
        "ptg-pagination": HTMLPtgPaginationElement;
        "ptg-radiobtn": HTMLPtgRadiobtnElement;
        "ptg-radiobuton": HTMLPtgRadiobutonElement;
        "ptg-select": HTMLPtgSelectElement;
        "ptg-sidenav": HTMLPtgSidenavElement;
        "ptg-spinner": HTMLPtgSpinnerElement;
        "ptg-table": HTMLPtgTableElement;
        "ptg-textarea": HTMLPtgTextareaElement;
        "ptg-toast": HTMLPtgToastElement;
        "ptg-ui-carousel": HTMLPtgUiCarouselElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PtgAccordion {
        "bgColor"?: string;
        /**
          * @default false
         */
        "defaultOpened"?: boolean;
        "description"?: string;
        "label"?: string;
    }
    interface PtgAlert {
        "appreanced"?: string;
        "buttoncss"?: string;
        "texed"?: string;
    }
    interface PtgBreadcrumbs {
        /**
          * @default []
         */
        "datalist"?: any;
    }
    interface PtgButton {
        "appearance"?: string;
        /**
          * @default 'right'
         */
        "btnIconAlignment"?: string;
        /**
          * @default ""
         */
        "text"?: string;
    }
    interface PtgCalender {
        "callback"?: (val: any) => void;
        /**
          * @default ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']
         */
        "dayNames"?: string[];
        /**
          * @default [     'January',     'February',     'March',     'April',     'May',     'June',     'July',     'August',     'September',     'October',     'November',     'December',   ]
         */
        "monthNames"?: string[];
        "onDayChanged"?: (event: PtgCalenderCustomEvent<any>) => void;
        "onMonthChanged"?: (event: PtgCalenderCustomEvent<any>) => void;
        /**
          * @default true
         */
        "showFillDays"?: boolean;
        "startDate"?: any;
    }
    interface PtgCard {
        /**
          * @default 'select'
         */
        "cardButtonText"?: string;
        /**
          * @default ''
         */
        "cardContent"?: string;
        "cardContentLength"?: number;
        "cardId"?: number;
        /**
          * @default ''
         */
        "cardTitle"?: string;
        /**
          * @default false
         */
        "isCardAction"?: boolean;
        "onHandleClick"?: (event: PtgCardCustomEvent<any>) => void;
        /**
          * @default ''
         */
        "src"?: string;
    }
    interface PtgCheckbox {
        "callback"?: (val: any) => void;
        /**
          * The first name
         */
        "checked"?: boolean;
        "color"?: string;
        "dataid"?: any;
        "datavalue"?: any;
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        "label"?: string;
        "onValueChanged"?: (event: PtgCheckboxCustomEvent<string>) => void;
    }
    interface PtgFooter {
        "footer"?: string;
    }
    interface PtgHeader {
        "header"?: string;
    }
    interface PtgInput {
        /**
          * id for input
         */
        "inputId"?: string;
        /**
          * label for inout
         */
        "label"?: string;
        /**
          * name for inout
         */
        "name"?: string;
        /**
          * Event emmiter to handle changes
         */
        "onValueChanged"?: (event: PtgInputCustomEvent<string>) => void;
        /**
          * The placeholder
          * @default ''
         */
        "placeholder"?: string;
        /**
          * type of input
         */
        "type"?: string;
        /**
          * name for inout
          * @default ''
         */
        "value"?: string;
        /**
          * @default '100%'
         */
        "width"?: string;
    }
    interface PtgModal {
        /**
          * @default ''
         */
        "btnName"?: string;
        /**
          * @default 'secondary'
         */
        "cancelBtn"?: string;
        /**
          * @default false
         */
        "closeOutsideClick"?: boolean;
        /**
          * @default 'Confirm'
         */
        "confirmButtonName"?: string;
        /**
          * @default false
         */
        "isOpen"?: boolean;
        /**
          * @default 'Modal Header'
         */
        "modalHeaderName"?: string;
        /**
          * @default 'md'
         */
        "modalSize"?: string;
        "onConfirmClose"?: (event: PtgModalCustomEvent<boolean>) => void;
        "onModalClose"?: (event: PtgModalCustomEvent<boolean>) => void;
        /**
          * @default 'primary'
         */
        "primaryBtn"?: string;
        /**
          * @default true
         */
        "showFooter"?: boolean;
        /**
          * @default true
         */
        "showHeader"?: boolean;
    }
    interface PtgPagination {
        "itemCount"?: number;
        "onPageChanged"?: (event: PtgPaginationCustomEvent<any>) => void;
        "onSizeChanged"?: (event: PtgPaginationCustomEvent<any>) => void;
        /**
          * @default 0
         */
        "page"?: number;
        /**
          * @default 10
         */
        "pageSize"?: number;
        /**
          * @default []
         */
        "pageSizeOptions"?: number[];
    }
    interface PtgRadiobtn {
        "ids"?: string;
        "name"?: string;
        "sender"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface PtgRadiobuton {
        "ids"?: string;
        "name"?: string;
        "sender"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface PtgSelect {
        /**
          * @default false
         */
        "multiSelect"?: boolean;
        "selectData"?: any;
    }
    interface PtgSidenav {
        "text"?: string;
        "url"?: string;
    }
    interface PtgSpinner {
        "appearance"?: string;
    }
    interface PtgTable {
        "customClass"?: string;
        /**
          * @default []
         */
        "pageSizeOptions"?: number[];
        /**
          * @default false
         */
        "searchable"?: boolean;
        /**
          * @default false
         */
        "sortable"?: boolean;
        "tableHover"?: boolean;
        "tableStrip"?: boolean;
        "tablecolumn"?: any;
        "tabledata"?: any;
        "tabletitle"?: string;
        "themeColor"?: string;
    }
    interface PtgTextarea {
        "appearance"?: string;
        "autofocus"?: boolean;
        "cols"?: number;
        "disable"?: boolean;
        "form"?: string;
        "maxlen"?: number;
        "minlength"?: number;
        "name"?: string;
        "placeholder"?: string;
        "readonly"?: boolean;
        "required"?: boolean;
        "rows"?: number;
        "value"?: string;
    }
    interface PtgToast {
        "appearance"?: string;
        "discription"?: string;
        "id1"?: string;
        /**
          * @default false
         */
        "open"?: boolean;
        "type"?: string;
    }
    interface PtgUiCarousel {
        /**
          * @default []
         */
        "images"?: Array<string>;
        /**
          * @default '200'
         */
        "imgHeight"?: string;
        /**
          * @default '200'
         */
        "imgWidth"?: string;
        /**
          * @default true
         */
        "showIndicators"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ptg-accordion": PtgAccordion;
        "ptg-alert": PtgAlert;
        "ptg-breadcrumbs": PtgBreadcrumbs;
        "ptg-button": PtgButton;
        "ptg-calender": PtgCalender;
        "ptg-card": PtgCard;
        "ptg-checkbox": PtgCheckbox;
        "ptg-footer": PtgFooter;
        "ptg-header": PtgHeader;
        "ptg-input": PtgInput;
        "ptg-modal": PtgModal;
        "ptg-pagination": PtgPagination;
        "ptg-radiobtn": PtgRadiobtn;
        "ptg-radiobuton": PtgRadiobuton;
        "ptg-select": PtgSelect;
        "ptg-sidenav": PtgSidenav;
        "ptg-spinner": PtgSpinner;
        "ptg-table": PtgTable;
        "ptg-textarea": PtgTextarea;
        "ptg-toast": PtgToast;
        "ptg-ui-carousel": PtgUiCarousel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ptg-accordion": LocalJSX.PtgAccordion & JSXBase.HTMLAttributes<HTMLPtgAccordionElement>;
            "ptg-alert": LocalJSX.PtgAlert & JSXBase.HTMLAttributes<HTMLPtgAlertElement>;
            "ptg-breadcrumbs": LocalJSX.PtgBreadcrumbs & JSXBase.HTMLAttributes<HTMLPtgBreadcrumbsElement>;
            "ptg-button": LocalJSX.PtgButton & JSXBase.HTMLAttributes<HTMLPtgButtonElement>;
            "ptg-calender": LocalJSX.PtgCalender & JSXBase.HTMLAttributes<HTMLPtgCalenderElement>;
            "ptg-card": LocalJSX.PtgCard & JSXBase.HTMLAttributes<HTMLPtgCardElement>;
            "ptg-checkbox": LocalJSX.PtgCheckbox & JSXBase.HTMLAttributes<HTMLPtgCheckboxElement>;
            "ptg-footer": LocalJSX.PtgFooter & JSXBase.HTMLAttributes<HTMLPtgFooterElement>;
            "ptg-header": LocalJSX.PtgHeader & JSXBase.HTMLAttributes<HTMLPtgHeaderElement>;
            "ptg-input": LocalJSX.PtgInput & JSXBase.HTMLAttributes<HTMLPtgInputElement>;
            "ptg-modal": LocalJSX.PtgModal & JSXBase.HTMLAttributes<HTMLPtgModalElement>;
            "ptg-pagination": LocalJSX.PtgPagination & JSXBase.HTMLAttributes<HTMLPtgPaginationElement>;
            "ptg-radiobtn": LocalJSX.PtgRadiobtn & JSXBase.HTMLAttributes<HTMLPtgRadiobtnElement>;
            "ptg-radiobuton": LocalJSX.PtgRadiobuton & JSXBase.HTMLAttributes<HTMLPtgRadiobutonElement>;
            "ptg-select": LocalJSX.PtgSelect & JSXBase.HTMLAttributes<HTMLPtgSelectElement>;
            "ptg-sidenav": LocalJSX.PtgSidenav & JSXBase.HTMLAttributes<HTMLPtgSidenavElement>;
            "ptg-spinner": LocalJSX.PtgSpinner & JSXBase.HTMLAttributes<HTMLPtgSpinnerElement>;
            "ptg-table": LocalJSX.PtgTable & JSXBase.HTMLAttributes<HTMLPtgTableElement>;
            "ptg-textarea": LocalJSX.PtgTextarea & JSXBase.HTMLAttributes<HTMLPtgTextareaElement>;
            "ptg-toast": LocalJSX.PtgToast & JSXBase.HTMLAttributes<HTMLPtgToastElement>;
            "ptg-ui-carousel": LocalJSX.PtgUiCarousel & JSXBase.HTMLAttributes<HTMLPtgUiCarouselElement>;
        }
    }
}
