export const resources = {
  IMG_LOGO: 'logo',
  LABEL_EMAIL: 'Email',
  INPUT_PLACEHOLDER_EMAIL: 'Enter your Email',
  LABEL_PASSWORD: 'Password',
  INPUT_PLACEHOLDER_PASSWORD: 'Enter your password',
  ERROR_MSG: 'Invalid email or password',
  LABEL_INFO_MSG: "If you don't have an account click on ",
  FORGOT_PASSWORD: 'Forgot Password',
  CANCEL: 'Cancel',
  SIGN_UP: 'SIGN UP',
  SIGN_IN: 'SIGN IN',
  LOG_IN: 'LOG IN',
  EMAIL_SENT: 'Email sent on your registered email.',
  REGISTRATION_TEXT: 'REGISTRATION',
  USER_NAME: 'User Name',
  ENTER_PASSWORD_PLACEHOLDER: 'Enter Password',
  USER_NAME_PLACEHOLDER: 'Enter User Name',
  REGISTRATION_LABEL_INFO_MSG: 'If you already have an account please click on',
  DECLARATION_REGISTRATION_TEXT: 'I here by declare that all the information provided are true to my knowledge.',
  DOB: 'DOB',
  CITY: 'City',
  GENDER: 'Gender',
  SUBMIT: 'Submit',
  CONFIRM_LABEL: 'I here by declare that all the information provided are true to my knowledge.',
  FOOTER_TEXT: `Copyright \u00A9 2022 Yash Technologies. All rights reserved.`,
  RESET_PASSWORD_TEXT: 'Reset Password',
  NEW_PASSWORD_TEXT: 'New Password',
  NEW_PASSWORD_PLACEHOLDER: 'Enter new password',
  OLD_PASSWORD_TEXT: 'Old Password',
  OLD_PASSWORD_PLACEHOLDER: 'Enter Old password',
  CONFIRM_PASSWORD_LABEL: 'Confirm Password',
  CONFIRM_PASSWORD_PLACEHOLDER: 'Re-enter your password',
  CONFIRM_PASSWORD_PLACEHOLDERE: 'Enter Confirm Password',
  LOADING: 'Loading...',
  LOGOUT: 'Logout',
  BAR_CHART_TEXT: 'Bar Chart',
  PIE_CHART_TEXT: 'Pie Chart',
  LINE_CHART_TEXT: 'Line Chart',
  LINE_BAR_CHART_TEXT: 'Line Bar Chart',
  CALENDAR_EXAMPLE_1: 'Calendar Example 1',
  CALENDAR_EXAMPLE_2: 'Calendar Example 2',
  CALENDAR_EXAMPLE_3: 'Calendar Example 3',
  CALENDAR_EXAMPLE_4: 'Calendar Example 4',
  MIN_DATE: 'Min Date',
  MAX_DATE: 'Max Date',
  BLUE_THEME: 'Blue Theme Calendar Example',
  RED_THEME: 'Green Theme Calendar Example',
  LOCALE_GERMANY: 'Calendar Example Germany',
  LOCALE_FRANCE: 'Calendar Example France',
  LOCALE_JAPAN:' Calendar Example Japan',
  SELECT_DATE: "Select Date",
  DATE_VALIDATOR_TEXT: 'Calender -Start & End Date Validator',
  START_DATE_TEXT: 'Start Date',
  START_DATE_VALIDATOR: 'Calender -Start Date Validator',
  END_DATE_TEXT: 'End Date',
  TODO_HEADER_TEXT: 'Your Tasks',
  INPUT_TODO_PLACEHOLDER: 'Enter a Task',
  DATE_ERROR_TEXT: 'Please select a valid date',
  FIRST_LETTER_CAPITAL_TEXT: 'First letter capitalize',
  INR_FORMAT_TEXT: 'INR format',
  TRUNCATE_PIPE_TEXT: 'Truncate Pipes',
  OUTPUT_TEXT: 'Output',
  ROLE_BASED_EXAMPLE_TEXT: 'Role Based Example',
  BUTTON_VISIBLE_FOR_ADMIN_ROLE_TEXT: 'Button Visible only For Admin Role',
  BUTTON_VISIBLE_FOR_EVERYONE_TEXT: 'Button Visible only For Everyone',
  ADD_USER_TEXT: 'Add User',
  EDIT_USER_TEXT: 'Edit User',
  VIEW_USER_TEXT: 'View User',
  SELECT_TEXT: 'Select',
  SINGLE_SELECT_TEXT: 'Single Select',
  MULTI_SELECT_TEXT: 'Multi Select',
  SELECT_PLACEHOLDER: 'Select',
  DATE_PLACEHOLDER: 'MM/DD/YYYY',
  WEB_ACCESSIBILITY_TEXT: 'Web Accessibility Example',
  HOW_TO_ACCESS: 'How to access',
  TAB_TEXT: 'Tab',
  KEY_FOR_FORWARD_CONTROL_TEXT: 'key for forword control',
  SHIFT_PLUS_TAB_TEXT: 'Shift + Tab',
  KEY_FOR_BACKWARD_CONTROL_TEXT: ' key for backword control',
  ALT_PLUS_U_TEXT: 'Alt + u',
  KEY_FOR_USERNAME_TEXT: ' key for username',
  ALT_PLUS_M_TEXT: 'Alt + m',
  KEY_FOR_EMAIL_TEXT: ' key for email',
  ALT_PLUS_G_TEXT: 'Alt + g',
  KEY_FOR_GENDER_TEXT: ' key for gender',
  ALT_PLUS_C_TEXT: 'Alt + c',
  KEY_FOR_CALENDER_TEXT: ' key for calender',
  ALT_PLUS_P_TEXT: 'Alt + p',
  KEY_FOR_PASSWORD_TEXT: ' key for password',
  ALT_PLUS_I_TEXT: 'Alt + i',
  KEY_FOR_CHECKBOX_TEXT: ' key for checkbox',
  ALT_PLUS_S_TEXT: 'Alt + s',
  KEY_FOR_SUBMIT_BUTTON_TEXT: ' key for submit button',
  INTERMEDIATE_CHECKBOX_TEXT: 'Indeterminate Checkbox',
  SIMPLE_SELECT_EX: 'Single Select Example',
  MULTI_SELECT_EX: 'Multi Select Example',
  SINGLE_SELECT: 'Single select',
  MULTI_SELECT: 'Multi select',
  SINGLE_LINE_CHART: 'Single Line Chart',
  MULTIPLE_LINE_CHART: 'Multiple Line Chart',
  LINE_BAR_CHART: 'Line Bar Chart',
  STACKED_CHART: 'Stacked Chart',
  PIE_CHART: 'Pie Chart',
  CONVERT_VALUE_USING_DIRECTIVE: 'Convert value using directive',
  CONVERT_VALUE_USING_EVENT: 'Convert value using event',
  CURRENCY_PIPES: 'Currency Pipes',
  PHONE_NUMBER_FORMATE_PIPES: 'Phone Number formate Pipes',
  CAPITALIZE_PIPES: 'Capitalize Pipes',
  TRUNCATE_PIPES: 'Truncate Pipes',
  ENTER_NUMBER_MY_NUMBER_PLACEHOLDER: 'Enter number my number',
  ENTER_NUMBER_PLACEHOLDER: 'Enter number',
  ENTER_TEXT_PLACEHOLDER: 'Enter text',
  NGX_DATATABLE: 'Ngx Datatable',
  MATERIAL_DATATABLE: 'Material Datatable',
  AG_GRID_DATATABLE: 'Ag Grid Datatable',
  DATATABLE_WITH_ACCORDIAN: 'Datatable With Accordian',
  ACHIEVED_IN_WEB_ACCESSIBILITY: {
    HEADING: 'What we achieved in Web Accessibility',
    ACHIEVED_POINTS: ['For every label we use "aria-label" and for the same every placeholder we used "aria-placeholder',
      'For every label we have to use "for" and for input id',
      'Whenever we use any image or logo, for that use proper alt text to understand why we use this image.',
      'when we use any color for like button or background color the color contrast are according to the Accessibility',
      'For readable plugin or read labels we have to pass tabindex = 0, so that the screen ready can ready the label also.']
  },
  FILE_DOWNLOAD: 'File Download',
  DRAG_DROP_EX_1: 'Example 1',
  DRAG_DROP_EX_2: 'Example 2',
  DRAG_DROP_EX_3: 'Example 3',
  DRAG_DROP_EX_4: 'Example 4',
  DRAG_DROP_EX_5: 'Example 5',
  CURRENT_DRAG_DROP_ACTION: 'current drag drop action:',
  TO_DO: 'To do',
  DONE_TEXT: 'Done',
  ADD_MANUAL: 'Add Manual',
  GRID_LAYOUT_EXAMPLE_HEADING: 'Grid Layout Example',
  ADD_SOME_QUICK_EX_TEXT: "Some quick example text to build on the card title and make up the bulk of the card's content.",
  CARD_TITLE_TEXT: 'Card title',
  GO_SOME_WHERE_TEXT: 'Go somewhere',
  GRID_LAYOUT_OFFSET_HEADING: 'Grid Layout with offset Example',
  TITLE: 'Salutation',
  TITLE_PLACEHOLDER: 'Select Salutation',
  LABEL_FIRST_NAME: 'First Name',
  LABEL_LAST_NAME: 'Last Name',
  FIRSTNAME_PLACEHOLDER: 'Enter First Name',
  LASTNAME_PLACEHOLDER: 'Enter Last Name'

};

//resources
