# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ptg-ui-apps

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install
        run: |
          npm install -f
      - name: npm build
        run: |
          npm run build:ui:current --if-present
      - name: Create directory if it does not exist
        run: |
          mkdir -p dist/apps/ptg-ui-apps-backend
      - name: Change to build directory
        run: |
          cd dist/apps/ptg-ui-apps-backend
      - name: npm install in dist
        run: |
          cd dist/apps/ptg-ui-apps-backend
           npm install -f
      - name: Upload node-app artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist/apps/ptg-ui-apps-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'yash-ui-apps'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32145BC8C8554972B10AAFAFC4A5BB7F }}
          package: .
